server:
  port: ${PORT:8081}
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: sistema_matricula
    password: Prueba$1
  mvc:
    favicon:
      enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
    open-in-view: true